- name: Get release timestamp
  command: date +%Y%m%d%H%M%S
  register: timestamp

- name: Get pretty release date
  command: date '+%Y-%m-%d %H:%M:%S'
  register: release_date

- name: Name release directory
  command: echo "{{ workspace }}/releases/{{ timestamp.stdout }}"
  register: release_path

- name: Creating release directory
  file: state=directory recurse=yes path={{ release_path.stdout }}

- name: Copying and unzipping GIT archive
  unarchive: src={{ jenkins_workspace }}//{{ deploy_archive_name }} dest={{release_path.stdout}}

- name: Change symlink
  file: state=link path={{ workspace }}/current src={{ release_path.stdout }}

- name: Keeping only 5 most recent builds
  script: remove-old-builds.sh {{ workspace }}/releases

- name: Migrate DB
  script: migrate.sh {{ workspace }} migrate {{ workspace }}/current
  when: db_migrate is defined and db_migrate=="true"

- name: Finalize app
  script: finalize.sh {{ workspace }}/current {{ workspace }}

