sudo: required
services:
- docker
language: node_js
node_js:
- '6'
install:
- docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d db
- docker-compose -f docker-compose.yml build # build for test env
- cd api
- npm install
- cd -
- cd app
- npm install
- cd -
script:
- docker-compose --version
- npm run db.migrate
- npm test
# also test down migrations
- npm run _db_migrate -- down --count 1000
- npm run db.migrate
- npm run db.test
after_success:
# push to dockerhub after push on successful push into master : build images and push
#  docker push $DOCKER_USERNAME/node-web-api;
#  docker push $DOCKER_USERNAME/node-web-app;
- if [ "$TRAVIS_BRANCH" == "master" ]; then
  DOCKER_USERNAME=$DOCKER_USERNAME API_URL=$API_URL PORT=4000 API_PORT=3000 PGADMINPASSWORD=postgres PGPASSWORD=give_me_time GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET GOOGLE_REDIRECT_URL=$GOOGLE_REDIRECT_URL docker-compose -f docker-compose.test.yml build;
  docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  docker push $DOCKER_USERNAME/node-web-api-test;
  docker push $DOCKER_USERNAME/node-web-app-test;
  fi
