sudo: required

services:
  - docker

language: node_js

before_install:
  - docker run --name server-db -it --rm -e POSTGRES_PASSWORD=postgres -e PG_PROJECT_USER=give_me_time -e PG_PROJECT_PASSWORD=give_me_time -e PG_PROJECT_DATABASE=give_me_time -v $(pwd)/server/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh -v $(pwd)/server/superuser.sql:/sql/superuser.sql -p 5430:5432 postgres

node_js:
  - "6"
  - "5"

script:
  - npm run db:migrate
  - npm test
  - npm run db:test