sudo: required
services:
- docker
language: node_js
node_js:
- '6'
install:
- docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d db
- docker-compose -f docker-compose.yml build # build for test env
- cd api
- npm install
- cd -
- cd app
- npm install
- cd -
script:
- docker-compose --version
- npm run db.migrate
- npm run db.test
# also test down migrations
- npm run _db_migrate -- down --count 1000
- npm run db.migrate
- npm run db.test
- npm run reset
- npm test
