sudo: required
services:
- docker
language: node_js
node_js:
- '6'
install:
- docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d db
- docker-compose -f docker-compose.yml build # build for test env
- cd api
- npm install
- cd -
- cd app
- npm install
- cd -
script:
- docker-compose --version
- npm run db.migrate
- npm test
# also test down migrations
- npm run _db_migrate -- down --count 1000
- npm run db.migrate
- npm run db.test


after_success:
# push to dockerhub after push on successful push into master
- if [ "$TRAVIS_BRANCH" == "master" ]; then
  # Build images
  docker-compose build
  docker login -u="givemetime" -p="$DOCKER_PASSWORD";
  docker push givemetime/node-web-api;
  docker push givemetime/node-web-app;
  fi
