sudo: required
services:
- docker
language: node_js
node_js:
- '6'
install:
- docker-compose -f docker-compose.yml build # build for test env
- docker-compose -f docker-compose.yml -f docker-compose.dev.yml build # build to run tests
- docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d db
script:
- docker-compose --version
- npm run db.migrate
- npm run db.test
# also test down migrations
- npm run _db_migrate -- down --count 1000
- npm run db.migrate
- npm run db.test
- npm test
after_success:
# https://sebest.github.io/post/using-travis-ci-to-build-docker-images/
- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
- export REPO=give-me-time/node-web-api
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
- export REPO=give-me-time/node-web-app
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
env:
  global:
  # API_URL
  - secure: xHqh/9jtYd77Hc+xfV+tW+1FwPE8QKpgken/JYSHtoakeMp8oOX7HmRLZ7SpHqsIRfoVyamkBfD47LC7+FYIlbN04vL5JnRSGzN/qj6+bAO/cyCbHXz10V7amJy74zpN2TqQdfJJ2KmdFmqEe32KVtu7JiNbRphb7GrbFSG+oVsG10RU9ufgd2eExzq1iRbNSnQJyMGXJz5aZtnov0zQUhs6AmuP5/V/uTQTdB8riV2C9dlKGY1NcF0ULXrKaGCvX0THQgHNAYxaE5bDW08lp2mG5vZsb+cZ4ykEUo3cPECWTE73YCzzC/PK/sR52bRuVM1maQY7TZNF3ZUbVopwXgA0DZdZDyiSG3OB3WJT3cbd2nxjrB72z6KB5Y8l8VSxHkX8e3pQ1ePlu3i0wXBQcbCZfgTUS5GS9qyu6QbnAWlnXkmnX4+zZm1kRdfDsUYy4ZMClgQfP6NiTsE5dWIGav6jRU/U4YHq+nsbbF/JuxhM2Lcsq4oaKS6ldF52daJtm9Psfx25bg2b6rEwHttTrm5ElW2iNsxF1wbqjaxXFn9I9slMv7fpFgBrbyTTiDM4abg0qUxJ3rQANCNX37apyDO2Wyf8NPbQMjgLdUD3dgKlatjRkAr/w94Fhji5ZFPKvtQIffXkKvcYXoalp8j42WoWFhYKdYtW7k5e0dr0Sjs=
  # GOOGLE_CLIENT_ID
  - secure: FuFgDbiGSGBXPLMIcIoGQxYk04iODV/6OLKeAw+95sLcYU5VpNigy/2LCDRdv+ISqhGB28v5AyuRM5KyHdszBdOjQ1tvk8qOqg4fFU5CqP2XSQC3h3Qd1nyz1CE6lXSG+xwZpcfgLTGv0YWv4o3cwxdtxoWRBhUlBGJGC6yQfdF1iNyJilI9TIoc+OskXnNlqP3g5u+vcyqT/fYIo29Rh+z4CxwzmyTQdnk6lNpweDr/PiOp5G96Yk72FqwsSPdiXBZ6KSSzpBVMHdMRR3nIocCBbGmnhE+usGZAjcV2YN1k7nafK33sccrZI1Ge0iwG6yOR0c0e847KBNFWm034LQcFmkRVW18DHgk1Lb6b9rmHzwGdjUD7SE6Zqm/LCgzzq56+Ok82FLCxVWrUCqDZZGLbrJOWT0er5DA6frPKtee3Vv9TAhsybYQWCKjDHsD5kQpVnCUP81JJ2nEGmBqA2jIKWOt19JCVW9DdsIlmbZmbDe4Pv49CE+bym9IcDceYxS6N9sFqUB+BBYBUN0jA1CaeIqBIaNMAIJmi8KcHxaQYwMCsT6zd/+EHlptfn87j+HJ9BiRUYUaBdAsdyx4DjagpZOROq/aJ/X4pov4wx3kjExXxsnhWYEOiPokctBWFpW3au/3Mazky6AapW1U61TOSWzD9XHr7BgY4W83F78U=
  # DOCKER_EMAIL
  - secure: GKg6SzdRm9A3DXQMY2FFOFVBgejjP/Kfk4vMStXCRBc99vVgnkybEBYx44OxDa7KcO5Zop2MIUWVGSQ5UOaCuXrlqRerqpKmgewQBwf7ygibfgtMccmjhfTFzo8bZd/G12/72SlKlLhIbgv5J773HKE9e43i1bzei1s7U72C+cgad26OFTS2kq0Q3ARHhLz4RGaxLXitB2vLxiMGyW4OJRpIJdFj6U0bqnWm7ze33YT6lFtZ06ujCOkI/gwl0a9qd08Y93NhI4Cp35co4bKpuWpvTOfem7PNetP5Xcvv+OxrnUtLaFMZlAOe+KTJLK5pjqQYXlJHkuq+IZH/HUgng/FEeYcEIDrogG1DYqZlRZBXqIjWB5hWIZ43RnK5JVCs1w/kLwvnPLZMVwEfDtNtoA9TC0RUVyOEDiS7WDquTtPTgUJL9UGg2XfQb5Gt+VrMnF80GHnc2FzWRJAbtwL/lI9cFC5sVsllnRuVT9tx6xwx+NOYhjpwG83iKmIiNpTp4cZetWPF8H3XMKsQKtZGVo9JQ/m7T6A62aXSq4P2OrILSXojuhAc8d+hR8yr2An+VihuMRQMMFz+qkZjcqwCL1wI1gqSr0UMIwDN+ocP1jjHsiSv3NxEnw4GVLPfoQrGgVuRRy6vDU6hRPGhnX5sH0/Pt5uu8zAZEHGhZcpQnAs=
  # DOCKER_USER
  - secure: VWU/N0tzrfcZkozIbMcCej5h0vYnpGMuwzinH+tSkYk9zlYu9LAVykL5xbt4Wj6VtepecmbScm+EUfRtdjLAQm+6NbqfXU/C+gARZEepb+IOZqa/2cZD0ufcetruqiMDFWZiI0evO/9TEm7DLjUBC59Tq275aI9dOvXOYLNiuVsB7VQaPAWWPT6u4qGkU/v4e/pxp87TtBW2NWdZeE/n2a8boOCOQove4KWqGNh5pOe8ZHO8b3clTtdZq0KA1841sWes+7Y/S+K5RBU5Ndg6kRvb1i/P+jLDgbNYgDtCiyHO6x72Ap5Xbd++MnREkjyFNO7H3XOnIRpvvnrK17xFWDNQiOU/YPQAMHxYJrIh/kV0k3kcv8QTJYSoZw7gEunXJWr9ekjjM0NCqk0aR7YP1QgVH5N3KtJDZ8547hZweKScoNxEIlkGUc3ulxo27/zVAKn5jzv0sKOZwWEX+/Bl98lnjxwoF+Q9NpTHX8gWFqqwXFE4bDH2IoEUEHPkfWC1cD5dlLzXV5FuzsmOXKsgDNwAmVplDI2TdSGTC4fyU8nNY23VW0aS9XVvEka9+k5tD8aS6XNyGchzSADNIr8Hvp2yTe7/CJSl+bi/S16h7DAha9N5yiEhTk7WmWsfxblp+zi2iefoyfgw1LjhvTshHzf6WOlMw+juXGBqWQefMWk=
  # DOCKER_PASS
  - secure: xdl8rLgjqp7Q0uoEjDbtfac4rxaQVBEbQW5tbRWD4vENRFQ/kbMokq5YTa2J/A8eea++cAya9CYyOcfPyKM99/GtwKBArl4ocShjycgqp4/qWhRO9iDndh9RksTlA/6hrZjYJ3W0rmqF0BPWX92vMWUjqd06NEz6ljTw9okWqX6oEKmxwpMb1K3xJvcv0BeTlIDWBnSW6gOam8dL57zP6ZF/XtX9jqCFZjTKGKL1/f/XR4NPA4wpON6yj9Q1HenKspMvRdgHlG2yGXbf6Hbj9dWeTeEo0e//BfuTvmoHgD8mlo7llHn94cgwgK0muKE0tWOF1CHHaka/Fhh60vSMAkGB3RR5l359gKZOmb9d5ZrMVVwRYl69r2wsjQzVTyR4KKSfsUJwD68sx/NsKwl7bT7IPYIPlkAN3nvuZivhYGmKTzlJfx5RaZtgjDELi8vROI67qbVH3JJrqZtUvgjqK4DInKJ2ZEey2f2Iy08G3gm8ZzLBxW2p9qDC4rDu4un/b8Fz14OomdojdLsml5LeENRYwmKniZQIZQcxs982JsEttQA9eRpA4I7PvYLI4szH2jGB8hfeeqp9RJ836FAeemPVvcE7qjaOEj/Xw+si08uwXQubYlwadqiwTYI8ooar1tmsu+cZyts9h28myUH+Gu6bgSBIq6MXTv83eSzQJ3U=
  - COMMIT: ${TRAVIS_COMMIT::8}
  - DOCKER_COMPOSE_VERSION: 1.8.1

